# Artificial Nerual Network

#### Preprocessing

In [58]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [59]:
dataset = pd.read_csv( 'Churn_Modelling.csv' )

X = dataset.drop( [ 'RowNumber', 'CustomerId', 'Surname', 'Exited' ], axis = 1 )
y = dataset[ 'Exited' ]

In [60]:
X = pd.get_dummies( X, columns = [ 'Geography', 'Gender' ], drop_first = True )

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
X_train, X_test, y_train, y_test = train_test_split( X, y, 
                                                     test_size = 0.25, 
                                                     random_state = 42 )

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler = StandardScaler()

In [65]:
X_train = pd.DataFrame( scaler.fit_transform( X_train ), columns = X_train.columns )
X_test  = pd.DataFrame( scaler.transform( X_test ), columns = X_test.columns )

C:\Users\scott\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\scott\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\scott\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  


In [10]:
X_train.head()

CreditScore       Age    Tenure   Balance  NumOfProducts  HasCrCard  \
0     0.218351  1.916619 -1.731689  1.629928       0.813111  -1.539736   
1     2.057280  0.202109  1.041750 -0.246244      -0.911043   0.649462   
2     0.758602 -0.750397  0.348390 -1.221027      -0.911043  -1.539736   
3    -0.082942 -0.559895  0.695070  1.574101      -0.911043  -1.539736   
4     0.530034 -0.940898  1.388429 -1.221027       0.813111   0.649462   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0        0.969789        -1.382844          -0.577761        -0.577350   
1       -1.031152        -1.195890           1.730820        -0.577350   
2       -1.031152        -0.683422          -0.577761        -0.577350   
3        0.969789        -0.985396          -0.577761        -0.577350   
4       -1.031152        -0.868375          -0.577761         1.732051   

   Gender_Male  
0     0.911867  
1     0.911867  
2    -1.096651  
3     0.911867  
4     0.911867

#### Build Artificial Nerual Network

In [66]:
import keras

In [75]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [13]:
# Define ANN as a sequence of layers
classifier = Sequential()

In [14]:
# .add allows you to add a hidden layer to the sequence of layers with dropout

# output_dim is the number of nodes in hidden layer
    # Rule-of-Thumb is N in input + N in output divided by 2
# init is the initial weight values
# activation is activation function
# input_dim is the number of input nodes
classifier.add( Dense( output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11 ) )
classifier.add( Dropout( p = 0.1 ) )

C:\Users\scott\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [15]:
# Add an additional hidden layer
classifier.add( Dense( output_dim = 6, init = 'uniform', activation = 'relu' ) )
classifier.add( Dropout( p = 0.1 ) )

C:\Users\scott\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [16]:
# Add the outpur layer
classifier.add( Dense( output_dim = 1, init = 'uniform', activation = 'sigmoid' ) )

C:\Users\scott\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [17]:
# Compile ANN with Stochastic Gradient Descent

# optimizer = algorithm to use to find optimum weights
# loss = loss function in sgd algorithm
# metrics = criterion used to eval model
classifier.compile( optimizer = 'adam', loss = 'binary_crossentropy', metrics = [ 'accuracy' ] )

In [19]:
classifier.fit( X_train, y_train, batch_size = 10, epochs = 100 )

Epoch 1/100
7500/7500 [==============================] - 1s 108us/step - loss: 0.4960 - acc: 0.7943
Epoch 2/100
7500/7500 [==============================] - 1s 67us/step - loss: 0.4316 - acc: 0.7947
Epoch 3/100
7500/7500 [==============================] - 0s 66us/step - loss: 0.4237 - acc: 0.8107
Epoch 4/100
7500/7500 [==============================] - 0s 63us/step - loss: 0.4170 - acc: 0.8316
Epoch 5/100
7500/7500 [==============================] - 0s 63us/step - loss: 0.4123 - acc: 0.8324
Epoch 6/100
7500/7500 [==============================] - 0s 62us/step - loss: 0.4090 - acc: 0.8340
Epoch 7/100
7500/7500 [==============================] - 0s 63us/step - loss: 0.4067 - acc: 0.8323
Epoch 8/100
7500/7500 [==============================] - 0s 60us/step - loss: 0.4054 - acc: 0.8307
Epoch 9/100
7500/7500 [==============================] - 0s 61us/step - loss: 0.4035 - acc: 0.8332
Epoch 10/100
7500/7500 [==============================] - 0s 63us/step - loss: 0.4031 - acc: 0.8327
Epoch 11

7500/7500 [==============================] - 0s 59us/step - loss: 0.3414 - acc: 0.8601
Epoch 84/100
7500/7500 [==============================] - 0s 57us/step - loss: 0.3425 - acc: 0.8565
Epoch 85/100
7500/7500 [==============================] - 0s 59us/step - loss: 0.3413 - acc: 0.8567
Epoch 86/100
7500/7500 [==============================] - 0s 59us/step - loss: 0.3419 - acc: 0.8577
Epoch 87/100
7500/7500 [==============================] - 0s 58us/step - loss: 0.3429 - acc: 0.8565
Epoch 88/100
7500/7500 [==============================] - 0s 58us/step - loss: 0.3434 - acc: 0.8544
Epoch 89/100
7500/7500 [==============================] - 0s 57us/step - loss: 0.3421 - acc: 0.8583
Epoch 90/100
7500/7500 [==============================] - 0s 58us/step - loss: 0.3418 - acc: 0.8577
Epoch 91/100
7500/7500 [==============================] - 0s 59us/step - loss: 0.3423 - acc: 0.8576
Epoch 92/100
7500/7500 [==============================] - 0s 59us/step - loss: 0.3435 - acc: 0.8569
Epoch 93/100


In [25]:
y_pred = classifier.predict( X_test )

In [29]:
y_pred = ( y_pred > 0.5 )

In [30]:
from sklearn.metrics import confusion_matrix, classification_report

In [31]:
print( confusion_matrix( y_test, y_pred ) )

[[1900  103]
 [ 255  242]]


In [32]:
print( classification_report( y_test, y_pred ) )

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      2003
           1       0.70      0.49      0.57       497

   micro avg       0.86      0.86      0.86      2500
   macro avg       0.79      0.72      0.74      2500
weighted avg       0.85      0.86      0.85      2500



#### Make New Prediction with Model

In [50]:
new_customer = np.array( [ [ 
    0, 
    0,
    600,
    1,
    40,
    3,
    60000,
    2,
    1,
    1,
    50000
] ] )

In [51]:
scaler.transform( new_customer )

C:\Users\scott\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-6.77373543e+00, -3.70316394e+00,  2.06276189e+02,
        -1.22101127e+00,  6.63309916e+01,  5.02785785e+00,
         1.20055435e+05, -1.74871668e+00,  1.73082000e+00,
         1.73205081e+00,  1.00424809e+05]])

In [52]:
new_pred = classifier.predict( new_customer )
new_pred = ( new_pred > 0.5 )

In [53]:
new_pred

array([[False]])

#### Evaluating the Artificial Neural Network with K-Fold Evaluation

In [76]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection     import cross_val_score, GridSearchCV

In [82]:
def build_classifier( optimizer = 'adam' ):
    classifier = Sequential()
    
    classifier.add( Dense( output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11 ) )
    classifier.add( Dense( output_dim = 6, init = 'uniform', activation = 'relu' ) )
    classifier.add( Dense( output_dim = 1, init = 'uniform', activation = 'sigmoid' ) )
    classifier.compile( optimizer = optimizer, loss = 'binary_crossentropy', metrics = [ 'accuracy' ] )
    
    return classifier

In [83]:
classifier = KerasClassifier( build_fn = build_classifier )

In [72]:
accuracies = cross_val_score( estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1 )

In [73]:
mean     = accuracies.mean()
variance = accuracies.std()

In [74]:
print( mean )
print( variance )

0.8374666617314022
0.01765295078615336


#### Tuning Artificial Neural Network with Grid Search

In [84]:
param_grid = {
    'batch_size' : [ 25, 32 ],
    'epochs'     : [ 100, 500 ],
    'optimizer'  : [ 'adam', 'rmsprop' ]
}

In [85]:
grid_search = GridSearchCV( estimator  = classifier,
                            param_grid = param_grid, 
                            scoring    = 'accuracy',
                            cv         = 10, 
                            n_jobs     = -1 )

In [86]:
# grid_search   = grid_search.fit( X_train, y_train )
# best_params   = grid_search.best_params_
# best_accuracy = grid_search.best_score_